name: Update to Latest Release

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: tvf-it-team/open-webui
          ref: main  # Explicitly checkout your fork's main branch
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/open-webui/open-webui.git || true

      - name: Fetch tags from upstream
        run: git fetch upstream --tags

      - name: Get latest tag
        id: latest_tag
        run: echo "latest_tag=$(git tag --sort=-v:refname | head -n 1)" >> $GITHUB_OUTPUT

      - name: Checkout latest tag and preserve custom-changes
        run: |
          git checkout tags/${{ steps.latest_tag.outputs.latest_tag }} -b update-to-${{ steps.latest_tag.outputs.latest_tag }}
          git checkout main -- custom-changes  # Restore custom-changes from your main branch

      - name: Copy custom binary files
        run: cp -r custom-changes/* .

      - name: Apply patches
        run: |
          for patch in custom-changes/patches/*.patch; do
            git apply "$patch" || { echo "Patch $patch failed to apply"; exit 1; }
          done

      - name: Commit changes
        run: |
          git add .
          git commit -m "Apply custom changes to ${{ steps.latest_tag.outputs.latest_tag }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply custom changes to ${{ steps.latest_tag.outputs.latest_tag }}"
          branch: update-to-${{ steps.latest_tag.outputs.latest_tag }}
          title: "Update to ${{ steps.latest_tag.outputs.latest_tag }} with custom changes"
          body: "This PR applies custom changes to the latest release ${{ steps.latest_tag.outputs.latest_tag }}."
